# Generated by Django 5.0.1 on 2024-04-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recurring', models.BooleanField(default=False, null=True)),
                ('term', models.CharField(max_length=20, null=True)),
                ('end_date', models.DateField()),
            ],
        ),
    ]
