# Generated by Django 5.0.4 on 2024-05-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_remove_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
