# Generated by Django 5.0.1 on 2024-05-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_remove_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
