# Generated by Django 5.0.4 on 2024-05-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_category_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
